language: python

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t dtok/water-data-allocation:$TRAVIS_BRANCH .
  - docker images
  - docker push dtok/water-data-allocation:$TRAVIS_BRANCH
