version: "2"

services:
    tasker:
        image: strm/tasker
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        environment:
             configuration: |
                 schedule:
                     - cron: 0 10 * * * *
                       task: consent-process
                 tasks:
                     docker:
                         - name: consent-process
                           image: dtok/water-data-allocation:dev
                           always-pull: true
                           volumes:
                               - /media/waterdata1/git/WaterDataConsents/parameters-dev.yml:/parameters.yml
                           script:
                               - python main.py parameters.yml
